spring:
  application:
    name: kafka-transactional-bug
  datasource:
    url: "jdbc:mysql://localhost:3306/bug_report?serverTimezone=UTC&createDatabaseIfNotExist=true"
    username: root
    password: root


kafka:
  bootstrap-servers: localhost:9092
  topicName: "example-topic"